#!/bin/bash

set -e
set -x

usage="usage: ${0} <script>"

script=$1
if [[ ! -n "$script" ]]; then
  echo $usage
  exit 1
fi

if [[ ! -f "$script" || ! -x "$script" ]]; then
  echo "${script} is not an executable regular file"
  exit 1
fi

echo "Running ${script} on ${box}..."
vagrant ssh precise64 -- -t "cd /vagrant && ./${script}"
