#! /bin/bash

set -e

source /etc/lsb-release

VERSION='1.4.18'
USER_VERSION='-ts1'

mkdir -p build
cd build

sudo apt-get install -y libevent-dev lsb-base perl

tarball_dir=memcached-${VERSION}
tarball=${tarball_dir}.tar.gz

if [[ ! -d $tarball_dir ]]; then
  if [[ ! -f $tarball ]]; then
    wget http://www.memcached.org/files/${tarball}
  fi
  tar zxvf $tarball
fi

cd $tarball_dir

./configure --prefix=/usr

make clean
make
make install DESTDIR=installdir
scripts_dir=installdir/usr/share/memcached/scripts
mkdir -p ${scripts_dir}
cp -pf scripts/{memcached-tool,start-memcached,memcached-init} ${scripts_dir}/

fpm -s dir -t deb -n ts-memcached -v ${VERSION}${USER_VERSION} -C installdir \
  --provides memcached --conflicts memcached \
  -p memcached-VERSION_ARCH.deb -d 'libc6 (>= 2.6)' \
  -d 'libevent-1.4-2 (>= 1.4.13-stable)' -d 'perl' -d 'lsb-base (>= 3.2-13)' \
  usr/bin usr/include usr/share

mkdir -p ../../debs/${DISTRIB_CODENAME}-tribesports
mv *.deb ../../debs/${DISTRIB_CODENAME}-tribesports
