#!/bin/bash

set -e

source /etc/lsb-release

VERSION='1.5.13'
USER_VERSION='-ts2'

mkdir -p build
cd build

sudo apt-get install -y build-essential libssl-dev zlib1g-dev libpcre3-dev libxslt-dev libxml2-dev libgeoip-dev

if [ ! -d nginx-${VERSION} ]; then
  wget http://nginx.org/download/nginx-${VERSION}.tar.gz
  tar zxvf nginx-${VERSION}.tar.gz
fi

cd nginx-${VERSION}

rm -rf objs Makefile

./configure \
  --prefix=/etc/nginx  \
  --sbin-path=/usr/sbin/nginx \
  --conf-path=/etc/nginx/nginx.conf  \
  --error-log-path=/var/log/nginx/error.log  \
  --http-client-body-temp-path=/var/lib/nginx/body  \
  --http-fastcgi-temp-path=/var/lib/nginx/fastcgi  \
  --http-log-path=/var/log/nginx/access.log  \
  --http-proxy-temp-path=/var/lib/nginx/proxy  \
  --http-scgi-temp-path=/var/lib/nginx/scgi  \
  --http-uwsgi-temp-path=/var/lib/nginx/uwsgi  \
  --lock-path=/var/lock/nginx.lock  \
  --pid-path=/var/run/nginx.pid  \
  --with-debug  \
  --with-http_addition_module  \
  --with-http_dav_module  \
  --with-http_geoip_module  \
  --with-http_gzip_static_module  \
  --with-http_realip_module  \
  --with-http_stub_status_module  \
  --with-http_ssl_module  \
  --with-http_sub_module  \
  --with-http_xslt_module  \
  --with-ipv6  \
  --with-sha1=/usr/include/openssl  \
  --with-md5=/usr/include/openssl  \
  --with-mail  \
  --with-mail_ssl_module

make
make install DESTDIR=installdir
mkdir -p installdir/var/lib/nginx

cat > preinstall_script <<END
#!/bin/bash
if [[ -f /etc/nginx/nginx.conf ]]; then
  cp /etc/nginx/nginx.conf{,.bak}
fi
END

cat > postinstall_script <<END
#!/bin/bash
if [[ -f /etc/nginx/nginx.conf.bak ]]; then
  mv /etc/nginx/nginx.conf{.bak,}
fi
service nginx restart
END

fpm -s dir -t deb -n ts-nginx -v ${VERSION}${USER_VERSION} -C installdir \
  --provides nginx --conflicts nginx \
  -p nginx-VERSION_ARCH.deb \
  -d "libc6 (>= 2.10)" -d "libgeoip1 (>= 1.4.6.dfsg)" \
  -d "libpcre3 (>= 7.7)" -d "libssl1.0.0" \
  -d "libxml2 (>= 2.7.4)" -d "libxslt1.1 (>= 1.1.18)" \
  -d "zlib1g (>= 1:1.1.4)" \
  --pre-install preinstall_script \
  --post-install postinstall_script \
  etc/nginx var usr/sbin

mkdir -p ../../debs/${DISTRIB_CODENAME}-tribesports
mv *.deb ../../debs/${DISTRIB_CODENAME}-tribesports
